"""How this controller reaches each fleet host: the inventory's `address`/`user`/`port`/
`identity_file` made real, instead of merely recorded.

fleet_inventory.py --probe-hosts records those fields per host (resolved from the LOCAL
`ssh -G`), but every ssh/rsync call in the fleet tooling used to be `ssh <host-name> ...`, so
the recorded fields changed nothing: per-host logins only worked if ~/.ssh/config already had a
matching `Host` block on the controller. This module closes that gap with ONE mechanism rather
than per-call-site flag plumbing: it renders the inventory into an OpenSSH config file and every
ssh/rsync call adds `-F <that file>`.

    Host linux-2
        HostName 10.0.0.7      (only when `address` differs from the host's name)
        User chewie
        Port 2222              (only when not 22)
        IdentityFile ~/.ssh/id_ed25519_fleet
        IdentitiesOnly yes     (only alongside an IdentityFile)
    Match all
    Include ~/.ssh/config

Why a config file and not `-l/-i/-p` argv: the same file also serves sync_findpeak_cache.sh
(`--ssh-config`), which is a shell script that only knows host names, and `ssh -G -F <file>
<host>` can verify the result for real without opening a connection.

PRECEDENCE: ssh takes the FIRST value it finds, so inventory blocks come first and WIN over the
user's own ~/.ssh/config for the fields they set. The user's config is still Included after
them, so everything the inventory does not say (ProxyJump, keepalives, ...) still applies. To
fall back to ~/.ssh/config for a field, delete that field from the inventory. A host with none
of these fields set gets no block at all, and with no blocks at all nothing is configured and
every call is byte-for-byte the plain `ssh <host>` it always was (see `active_config()`).

The rendered file is content-addressed (`<sha16>.conf` under ~/.cache/parametric-nam/ssh/), so
concurrent processes with the same inventory share one file and nothing needs cleaning up.
"""
from __future__ import annotations

import hashlib
import os
import re
import shlex
from pathlib import Path

_active: "Path | None" = None

_BAD_NAME = re.compile(r"[\s*?!,]")   # ssh_config Host patterns: wildcards, negation, lists


def default_cache_dir() -> Path:
    return Path("~/.cache/parametric-nam/ssh").expanduser()


def _val(v) -> str:
    """One ssh_config argument. Quoted when it has whitespace; a literal double quote can't be
    represented safely, so refuse rather than emit something ssh would parse differently."""
    s = str(v)
    if '"' in s or "\n" in s or "\r" in s:
        raise ValueError(f"unsupported character in ssh config value: {s!r}")
    return f'"{s}"' if any(c.isspace() for c in s) else s


def host_block(name: str, entry: dict) -> "list[str] | None":
    """The `Host` block for one inventory host, or None when the inventory says nothing that
    differs from plain `ssh <name>` (so an unconfigured host keeps resolving through the
    operator's own ~/.ssh/config exactly as before)."""
    if _BAD_NAME.search(name):
        raise ValueError(f"inventory host name {name!r} is not usable as an ssh Host alias")
    lines = []
    address = entry.get("address")
    if address and address != name:
        lines.append(f"    HostName {_val(address)}")
    if entry.get("user"):
        lines.append(f"    User {_val(entry['user'])}")
    port = entry.get("port")
    if port and int(port) != 22:
        lines.append(f"    Port {int(port)}")
    if entry.get("identity_file"):
        lines.append(f"    IdentityFile {_val(entry['identity_file'])}")
        lines.append("    IdentitiesOnly yes")
    if not lines:
        return None
    return [f"Host {name}"] + lines


def render_ssh_config(inv: dict, user_config: str = "~/.ssh/config") -> "str | None":
    """The full config text for `inv`, or None when no host needs a block."""
    blocks = []
    for name in sorted(inv):
        b = host_block(name, inv[name] or {})
        if b:
            blocks.append("\n".join(b))
    if not blocks:
        return None
    # `Match all` matters: Include is conditional on the enclosing Host/Match block, so a bare
    # Include after the last Host block would only apply to that one host.
    head = "# generated by ssh_target.py from the fleet inventory -- do not edit\n"
    return head + "\n".join(blocks) + f"\nMatch all\nInclude {_val(user_config)}\n"


def write_config(text: str, cache_dir: "Path | None" = None) -> Path:
    cache_dir = Path(cache_dir) if cache_dir else default_cache_dir()
    cache_dir.mkdir(parents=True, exist_ok=True)
    path = cache_dir / f"{hashlib.sha256(text.encode()).hexdigest()[:16]}.conf"
    if not path.exists():
        tmp = path.with_name(f".{path.name}.{os.getpid()}.tmp")
        tmp.write_text(text)
        os.chmod(tmp, 0o600)          # ssh refuses a config that others can write
        os.replace(tmp, path)
    return path


def configure(inventory_path: "Path | None" = None, *, cache_dir: "Path | None" = None,
              user_config: str = "~/.ssh/config") -> "Path | None":
    """Load the inventory (None = its default location; a missing file is just an empty
    inventory), render it, and make every later ssh_argv()/rsync_e() in this process use it.
    Returns the config path, or None when nothing needs configuring."""
    global _active
    import fleet_inventory                # lazy: fleet_inventory imports cpu_topology -> here
    inv = fleet_inventory.load_inventory(inventory_path)
    text = render_ssh_config(inv, user_config)
    _active = write_config(text, cache_dir) if text else None
    return _active


def reset() -> None:
    global _active
    _active = None


def active_config() -> "Path | None":
    return _active


def ssh_argv(host: str, *opts: str) -> "list[str]":
    """`ssh [-F cfg] <opts...> <host>` -- the caller appends the remote command."""
    base = ["ssh"] + (["-F", str(_active)] if _active else [])
    return base + list(opts) + [host]


def rsync_e() -> "list[str]":
    """`-e "ssh -F cfg"` for an rsync call, or nothing when no config is active."""
    return ["-e", f"ssh -F {shlex.quote(str(_active))}"] if _active else []
